#ifndef _THORVG_FLUTTER_ANDROID_CONFIG_H_
#define _THORVG_FLUTTER_ANDROID_CONFIG_H_

#define THORVG_VERSION_STRING "1.0.3"

#define THORVG_SW_RASTER_SUPPORT 1
#define THORVG_THREAD_SUPPORT 1
#define THORVG_FILE_IO_SUPPORT 1

#define THORVG_LOTTIE_LOADER_SUPPORT 1
#define THORVG_PNG_LOADER_SUPPORT   1
#define THORVG_JPG_LOADER_SUPPORT   1

#endif
